// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsfakhthcuroytuzkhvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZmFraHRoY3Vyb3l0dXpraHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTI1ODAsImV4cCI6MjA2OTAyODU4MH0.iRUwTefIZLt8Pq_eivEGAWjOfvlRVEbEMcx8rKgDeH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});